baseURL = 'https://shubhangibw.github.io/stackwebsite/'
languageCode = 'en-us'
title = 'ABLOG'
theme = 'stack'
[Params.Sidebar]
    subtitle = "currently working on enabling comments on cards"
    description = "I DONT SEE THIS"
    compact = false
    avatar.enabled = true
    avatar.src = "/stackwebsite/images/cropped-AMON.jpg"
    avatar.local = false

[Params.Comments.utterances]
    enabled = true
    provider='utterances'
    repo = "shubhangibw/stackwebsite"
    issueTerm = "pathname"
    label = "blog-comment"
    theme = "github-dark"
    crossorigin = "anonymous"