baseURL = 'https://shubhangibw.github.io/stackwebsite/'
languageCode = 'en-us'
title = 'User Blog'
theme = 'stack'
[Params.Sidebar]
    subtitle = "A blog by Shubhangi"
    compact = true
    avatar.enabled = true
    avatar.src = "me.jpg"
    avatar.local = false