baseURL = 'https://shubhangibw.github.io/stackwebsite/'
languageCode = 'en-us'
title = 'User Blog'
theme = 'stack'
[Params.Sidebar]
    subtitle = "For Yourself"
    description = "A personal blog"
    compact = false
    avatar.enabled = true
    avatar.src = "/stackwebsite/static/images/me.jpg"
    avatar.local = false